### ISSUE TITLE
invalid json response body

### ISSUE THREAD

**Issue by Terkea** [codeSTACKr/video-source-code-create-nft-collection#1]
Hi there,
I was just trying to follow along with the tutorial you've made but every time I try to upload the files to the IPFS I get this error. 

```javascript
FetchError: invalid json response body at https://api.nftport.xyz/v0/files reason: Unexpected token < in JSON at position 0
    at /mnt/c/Users/terke/Desktop/work/degenerate-pixels/node_modules/node-fetch/lib/index.js:273:32
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  type: 'invalid-json'
}
```

**Comment by codeSTACKr** [comment]
It looks like you are sending invalid json to the server. Be sure to double check that your code matches the examples.

**Comment by Mustache1** [comment]
Hello, 

I keep getting this message after I run node utils/nftport/uploadFiles.js. 

error:FetchError: invalid json response body at https://api.nftport.xyz/v0/files reason: Unexpected token < in JSON at position 1

**Comment by Merc616** [comment]
bump

**Comment by Gitisgit** [comment]
same here

**Comment by Terkea** [comment]
the problem comes from their API which cant handle all the requests at the same time.

this can be fixed by adding a delay in between the requests.

**Comment by StartUpDream** [comment]
How do you add a delay?

**Comment by GangSti1e** [comment]
I have got the same problem. Any fix?

**Comment by naadis** [comment]
Same problem here. Any one got a solution?

**Comment by NAXIG** [comment]
i Have the same error. what can i do?
