### ISSUE TITLE
error:FetchError: invalid json response body at https://api.nftport.xyz/v0/files reason: Unexpected token < in JSON at position 1

### ISSUE THREAD

**Issue by not-myactualname** [codeSTACKr/video-source-code-create-nft-collection#11]
Has somenone figured this out?
I'm getting the error when i try to upload the images to IPFS:

error:FetchError: invalid json response body at https://api.nftport.xyz/v0/files reason: Unexpected token < in JSON at position 1
error:FetchError: invalid json response body at https://api.nftport.xyz/v0/files reason: Unexpected token < in JSON at position 1
error:FetchError: invalid json response body at https://api.nftport.xyz/v0/files reason: Unexpected token < in JSON at position 1
error:FetchError: invalid json response body at https://api.nftport.xyz/v0/files reason: Unexpected token < in JSON at position 1
...and so on, for each image.
I've checked the code many times but I'm still missing something, please help if you can.

**Comment by codeSTACKr** [comment]
fixed with latest code:
https://github.com/codeSTACKr/video-source-code-create-nft-collection/tree/fix-uploads-mints
