### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'edition')

### ISSUE THREAD

**Issue by hendrikegn** [codeSTACKr/video-source-code-create-nft-collection#14]
Hello ! I'm getting this error when trying to upload the uploadMetas.js file with the fix code provided, not sure what I'm doing wrong.
Thank you!

_h_v1> node utils/nftport/uploadMetas.jsC:\Users\hendr\Downloads\hashlips_art_engine-1.1.2_patch_v1\hashlips_art_engine-1.1.2_patch_v1\utils\nftport\uploadMetas.js:29          return item.custom_fields.edition === metaData.custom_fields.edition;
                                    ^

TypeError: Cannot read properties of undefined (reading 'edition')
    at C:\Users\hendr\Downloads\hashlips_art_engine-1.1.2_patch_v1\hashlips_art_engine-1.1.2_patch_v1\utils\nftport\uploadMetas.js:29:37    at Array.find (<anonymous>)
    at C:\Users\hendr\Downloads\hashlips_art_engine-1.1.2_patch_v1\hashlips_art_engine-1.1.2_patch_v1\utils\nftport\uploadMetas.js:28:40    at FSReqCallback.oncomplete (node:fs:188:23)
PS C:\Users\hendr\Downloads\hashlips_art_engine-1.1.2_patch_v1\hashlips_art_engine-1.1.2_patch_v1> ^CPS C:\Users\hendr\Downloads\hashlips_art_engine-1.1.2_patch_v1\hashlips_art_engine-1.1.2_patch_v1>_

**Comment by hendrikegn** [comment]
Got it fixed !
I erased the _ipfsMetas.json file under json and ran the uploadMeta.js file again. Everything was updated !

**Comment by jones0770** [comment]
> Got it fixed ! I erased the _ipfsMetas.json file under json and ran the uploadMeta.js file again. Everything was updated !

Can you show what you did exactly ?

**Comment by jones0770** [comment]
Where you got _ipfsMetas.json file?
