### ISSUE TITLE
Error [ERR_REQUIRE_ESM]

### ISSUE THREAD

**Issue by siaa99** [codeSTACKr/video-source-code-create-nft-collection#15]
Hello! I'm facing some issues after I ran 'node utils/nftport/uploadFiles.js'. Can anyone help me? Thank you.
![Screenshot 2022-01-01 at 9 04 36 PM](https://user-images.githubusercontent.com/95530463/147851233-e2277b38-9b51-489c-af38-7ad659f1852b.png)

**Comment by codeSTACKr** [comment]
The solution is in the Readme instructions
