### ISSUE TITLE
error:FetchError: invalid json response body at https://api.nftport.xyz/v0/files reason: Unexpected token < in JSON at position 1

### ISSUE THREAD

**Issue by craigbersiks** [codeSTACKr/video-source-code-create-nft-collection#18]
Hi,

I have been following along with the video (amazing by the way 👍 ) and I have come across this error whenever I try the node utils/nftport/uploadfiles.js

error:FetchError: invalid json response body at https://api.nftport.xyz/v0/files reason: Unexpected token < in JSON at position 1

Not sure what I have done wrong as I have checked the code multiple times.

**Comment by codeSTACKr** [comment]
the updated code here fixes this issue:
https://github.com/codeSTACKr/video-source-code-create-nft-collection/tree/fix-uploads-mints/utils/nftport

**Comment by craigbersiks** [comment]
Thank you so much!! will try again later on today. I can still follow along on the vid and do exactly what is shown?
