### ISSUE TITLE
if(!metaData.file_url.includes('https://')) {

### ISSUE THREAD

**Issue by craigbersiks** [codeSTACKr/video-source-code-create-nft-collection#20]
Hi,

Thank you for the update! looking great.

I seem to be getting this error now:

if(!metaData.file_url.includes('https://')) {........... TypeError: Cannot read properties of undefined (reading 'includes')

I am not sure what I am doing wrong.

**Comment by ryuncoding** [comment]
Im having same problem

**Comment by codeSTACKr** [comment]
seems like some of your metadata doesn't have a file_url? Can you provide an example of a json file from the build folder?

**Comment by ryuncoding** [comment]
Yes its about that i have already checked. Thanks. I built my images and json files with old version of config.js. I updated my config.js with your latest version and I rebuild my NFTs and it fixed. Thanks a lot.

**Comment by craigbersiks** [comment]
const basePath = process.cwd();
const { MODE } = require(`${basePath}/constants/blend_mode.js`);
const { NETWORK } = require(`${basePath}/constants/network.js`);

const network = NETWORK.eth;

// General metadata for Ethereum
const namePrefix = "MysteryOrb";
const description = "Orb Collection";
const baseUri = "ipfs://NewUriToReplace";

const solanaMetadata = {
  symbol: "YC",
  seller_fee_basis_points: 1000, // Define how much % you want from secondary market sales 1000 = 10%
  external_url: "https://www.youtube.com/c/hashlipsnft",
  creators: [
    {
      address: "7fXNuer5sbZtaTEPhtJ5g5gNtuyRoKkvxdjEjEnPN4mC",
      share: 100,
    },
  ],
};

// If you have selected Solana then the collection starts from 0 automatically
const layerConfigurations = [
  {
    growEditionSizeTo: 20,
    layersOrder: [
      { name: "Background" },
      { name: "Cloud" },
      { name: "Shadow" },
      { name: "Orb" },
    ],
  },
];

const shuffleLayerConfigurations = false;

const debugLogs = false;

const format = {
  width: 750,
  height: 512,
  smoothing: false,
};

const gif = {
  export: false,
  repeat: 0,
  quality: 100,
  delay: 500,
};

const text = {
  only: false,
  color: "#ffffff",
  size: 20,
  xGap: 40,
  yGap: 40,
  align: "left",
  baseline: "top",
  weight: "regular",
  family: "Courier",
  spacer: " => ",
};

const pixelFormat = {
  ratio: 2 / 128,
};

const background = {
  generate: true,
  brightness: "80%",
  static: false,
  default: "#000000",
};

const extraMetadata = {};

const rarityDelimiter = "#";

const uniqueDnaTorrance = 10000;

const preview = {
  thumbPerRow: 5,
  thumbWidth: 50,
  imageRatio: format.height / format.width,
  imageName: "preview.png",
};

const preview_gif = {
  numberOfImages: 5,
  order: "ASC", // ASC, DESC, MIXED
  repeat: 0,
  quality: 100,
  delay: 500,
  imageName: "preview.gif",
};

module.exports = {
  format,
  baseUri,
  description,
  background,
  uniqueDnaTorrance,
  layerConfigurations,
  rarityDelimiter,
  preview,
  shuffleLayerConfigurations,
  debugLogs,
  extraMetadata,
  pixelFormat,
  text,
  namePrefix,
  network,
  solanaMetadata,
  gif,
  preview_gif,
};

**Comment by craigbersiks** [comment]
{
  "name": "MysteryOrb #1",
  "description": "Orb Collection",
  "image": "ipfs://NewUriToReplace/1.png",
  "dna": "206e32739e05ba470d7d1a3897c44869d1a365ee",
  "edition": 1,
  "date": 1641313918556,
  "attributes": [
    {
      "trait_type": "Background",
      "value": "Marble Lab"
    },
    {
      "trait_type": "Cloud",
      "value": "Cloud"
    },
    {
      "trait_type": "Shadow",
      "value": "Here's Reddy"
    },
    {
      "trait_type": "Orb",
      "value": "Yellow Blue Spotty"
    }
  ],
  "compiler": "AfricanMystery"
}

**Comment by craigbersiks** [comment]
Fixed it, Thank you

**Comment by niveknonrev** [comment]
I'm having the same issue TypeError: Cannot read properties of undefined (reading 'includes') - checked my config.js and it matches, and my JSON files have the File_url  - here is an example "File_url": "ipfs://NewUriToReplace/1.png",

any other suggestions on what to look at?

**Comment by engmsaleh** [comment]
I have faced the same issue and found that Hashlibs now uses `image` instead of `file_url` in a function called `addMetaData` in main.js

**Comment by Denni007** [comment]
Hi All 

I solved this error, which I was getting when applying "includes" to a "!metaData.file_url.includes('https://'" value, by appending ".toString();"
`if(!metaData.file_url.toString().includes("https://")) {`

The .includes() API is part of the String and Array data type.

So what the error is trying to tell you is that the value for variable value, e.g. an integer or json object, does not have the property .includes.
