### ISSUE TITLE
Does not build, loads of errors

### ISSUE THREAD

**Issue by Nerred** [codeSTACKr/video-source-code-create-nft-collection#21]
Node is installed but when running npm install in root folder it wont build.
it seems to have issue installing Canvas and node-gyp dont work and some missing dlls are:

npm ERR! C:\GTK\bin\zlib1.dll
npm ERR! C:\GTK\bin\libglib-2.0-0.dll
npm ERR! C:\GTK\bin\libfreetype-6.dll
npm ERR! C:\GTK\bin\libgthread-2.0-0.dll
npm ERR! C:\GTK\bin\libgobject-2.0-0.dll
npm ERR! C:\GTK\bin\libpangowin32-1.0-0.dll
npm ERR! C:\GTK\bin\libfontconfig-1.dll
npm ERR! C:\GTK\bin\libpangocairo-1.0-0.dll
npm ERR! C:\GTK\bin\libexpat-1.dll
npm ERR! C:\GTK\bin\libgmodule-2.0-0.dll
npm ERR! C:\GTK\bin\libpango-1.0-0.dll
npm ERR! C:\GTK\bin\libpangoft2-1.0-0.dll
npm ERR! C:\GTK\bin\libintl-8.dll
npm ERR! C:\GTK\bin\libcairo-2.dll
npm ERR! C:\GTK\bin\libpng14-14.dll

**Comment by codeSTACKr** [comment]
This is an issue with your local installation of node.js. You should uninstall and reinstall it.
