### ISSUE TITLE
CATCH ERROR: TypeError: Cannot read properties of undefined (reading 'response')

### ISSUE THREAD

**Issue by ChristianErdtmann** [codeSTACKr/video-source-code-create-nft-collection#23]
Hey i followed the steps in the toturial but when i try to run "node utils/nftport/uploadFiles.js"
I got the following error.

Windows PowerShell
Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.

Lernen Sie das neue plattformübergreifende PowerShell kennen – https://aka.ms/pscore6

PS C:\NFTMinter1000Oversea\NewCodeErrorFixed\video-source-code-create-nft-collection> node utils/nftport/uploadFiles.js
ERROR STATUS: 403
Retrying
CATCH ERROR: TypeError: Cannot read properties of undefined (reading 'response')
Retrying
ERROR STATUS: 403
Retrying
CATCH ERROR: TypeError: Cannot read properties of undefined (reading 'response')
Retrying
ERROR STATUS: 403
Retrying
ERROR STATUS: 403
Retrying
CATCH ERROR: TypeError: Cannot read properties of undefined (reading 'response')
Retrying
CATCH ERROR: TypeError: Cannot read properties of undefined (reading 'response')
Retrying
ERROR STATUS: 403

**Comment by codeSTACKr** [comment]
403 is a security issue. Most likely your API key is incorrect.

**Comment by ChristianErdtmann** [comment]
The API Key is correct but the error still happens

**Comment by aqeel0106** [comment]
u have to save the file first by pressing ctrl+s or from the file menu after u add your api key

**Comment by MetaAlcoholClub** [comment]
I've got the same issue. I already uploaded more thank 3k metas, every 20 more or less get me that issue so is not the API
