### ISSUE TITLE
the updated code here fixes this issue:

### ISSUE THREAD

**Issue by Jakeblackfield** [codeSTACKr/video-source-code-create-nft-collection#24]
Hey there, 
thanks for the awesome video you did. 

I only have a question. I can't manage to upload the files to ipfs and I saw that you made a new version of the code that should fix this but the link you sent doesn't work...
this one: (taken from another issue report)

the updated code here fixes this issue:
https://github.com/codeSTACKr/video-source-code-create-nft-collection/tree/fix-uploads-mints/utils/nftport

I supposed it's the new version of the code you posted yesterday. If I download it do I have to do everything from the beginning again modifying all the things you say in the video? I was almost at the end of the procedure it would be a shame 😞

_Originally posted by @codeSTACKr in https://github.com/codeSTACKr/video-source-code-create-nft-collection/issues/18#issuecomment-1004307982_

**Comment by burgs11** [comment]
what happened to the link? I think i need this to fix my upload issue as well
