### ISSUE TITLE
metadata upload stopped 

### ISSUE THREAD

**Issue by Jakeblackfield** [codeSTACKr/video-source-code-create-nft-collection#25]
Hi,
thanks for the new version of the code.
I 'm at the point where I upload the metadata .json to ipfs, all was working fine but it stopped uploading at 740 of 6969 files. what can I do?

thanks.

**Comment by ryuncoding** [comment]
I am having same problem.

**Comment by codeSTACKr** [comment]
You can stop the upload by pressing CTRL+C, then restart it. It will pick up where it left off. I'm not sure why it would just stop.
