### ISSUE TITLE
Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by BeatKO** [codeSTACKr/video-source-code-create-nft-collection#26]
When running 
node utils/nftport/genericMetas.js

i get this error:

delete jsonFile.custom_fields.dna;
                  ^
TypeError: Cannot convert undefined or null to object

**Comment by codeSTACKr** [comment]
does your json files not have the dna field?

**Comment by BeatKO** [comment]
it has.

  "name": "test #2",
  "description": "Unique test test",
  "image": "ipfs://NewUriToReplace/2.png",
  "dna": "testnumber",
  "edition": 2,
  "date": 1641415744625,
  "attributes": [

**Comment by BeatKO** [comment]
So it worked for me when i changed this line:

  **delete jsonFile.custom_fields.dna;**
to this:
  **delete jsonFile.dna;**

**Comment by codeSTACKr** [comment]
yeah, your json file is not formatted the way it's looking for. So this wouldn't be an issue with the code.
