### ISSUE TITLE
ERROR STATUS 429

### ISSUE THREAD

**Issue by Jakeblackfield** [codeSTACKr/video-source-code-create-nft-collection#27]
Is there a way to solve this error? 
ERROR STATUS: 429
Retrying
CATCH ERROR: TypeError: Cannot read properties of undefined (reading 'response')

Thanks!

**Comment by MintPunk** [comment]
I am having the same issue when i try to run Mint.js 
I'm stuck here and need help. badly. Any help would be appreciated.

**Comment by DiggsKoala** [comment]
Have test collection minted on rinkeby. When running revealNFTs.js get

CATCH ERROR: TypeError: Cannot read properties of undefined (reading 'response')
Retrying
ERROR STATUS: 422

ERROR STATUS: 429

**Comment by codeSTACKr** [comment]
This was an oversight on my part. This API does not work with Rinkeby, only Polygon. You will not get those errors when using Polygon.
