### ISSUE TITLE
Uploading files error

### ISSUE THREAD

**Issue by thorsa12** [codeSTACKr/video-source-code-create-nft-collection#3]
My console logged the following and with every run at random: 

8.png uploaded & 8.json updated!
error:TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
error:TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
error:TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
15.png uploaded & 15.json updated!
9.png uploaded & 9.json updated!
...

Any ideas?

**Comment by thorsa12** [comment]
npm install react-scripts@latest  

didnt help

**Comment by bluedoy** [comment]
did you manage to find the solution tried

**Comment by thorsa12** [comment]
I manged to upload and update all 5 ones after defining 

const _editionCount = String(_editionCount)

in main.js 

but I have no clue if this was just luck or if its right. im not a coder haha. still stuck on all the steps after that.

**Comment by codeSTACKr** [comment]
I've fixed this issue by re-writing some of the code. I've added the updates to a new branch. 
https://github.com/codeSTACKr/video-source-code-create-nft-collection/tree/fix-uploads-mints
