### ISSUE TITLE
NOK: Minting limit exceeded on rinkeby and Minted ones not showing on opensea testnets

### ISSUE THREAD

**Issue by Jakeblackfield** [codeSTACKr/video-source-code-create-nft-collection#30]
Hi,
I'm at the mint.js stage and at the 1000 minted I get this error:

NOK: Minting limit exceeded on rinkeby

plus, I don't see the minted ones displaying on opensea testnets.

what could it be? 

thanks in advance.

**Comment by ryuncoding** [comment]
I am having same problem.

**Comment by codeSTACKr** [comment]
You are limited to 1000 mints per chain. You will need to apply for the community plan or use the paid plan to mint more.

**Comment by Jakeblackfield** [comment]
ok, thanks. and do you happen to know why I can't see the 1000 already minted on OpenSea testnet?
