### ISSUE TITLE
revealNFTs.js

### ISSUE THREAD

**Issue by ChristianErdtmann** [codeSTACKr/video-source-code-create-nft-collection#33]
Hey i watched you Youtube video.
But there is no revealNFTs.js inside.

What do revealNFTs? When does it have to be called?
Is the right order:
node utils/nftport/uploadFiles.js
node utils/nftport/genericMetas.js
node utils/nftport/uploadMetas.js
node utils/nftport/revealNFTs.js
node utils/nftport/mint.js
?

**Comment by John8790909** [comment]
No you reveal the nfts after you minted the generic data

**Comment by DiggsKoala** [comment]
Have test collection minted on rinkeby. When running revealNFTs.js get

CATCH ERROR: TypeError: Cannot read properties of undefined (reading 'response')
Retrying
ERROR STATUS: 422

ERROR STATUS: 429

**Comment by ChristianErdtmann** [comment]
Yes for me the same i now tried to revealNFTs and get the error:

ERROR STATUS: 429
Retrying
CATCH ERROR: TypeError: Cannot read properties of undefined (reading 'response')
Retrying
NOK: Unexpected error, try again in a short while

**Comment by codeSTACKr** [comment]
duplicate #27
