### ISSUE TITLE
ERROR STATUS: 403

### ISSUE THREAD

**Issue by ChristianErdtmann** [codeSTACKr/video-source-code-create-nft-collection#34]
Hey i still got the same error.
I checked my api key and in a older version the key works for the upload but some images got an error.
I cloned the newest version and inserted the api key but it dont work.
I alltimes get the following error:

PS C:\NFTMinter1000Oversea\video-source-code-create-nft-collection> node utils/nftport/uploadFiles.js
ERROR STATUS: 403
Retrying
CATCH ERROR: TypeError: Cannot read properties of undefined (reading 'response')

Some idea?

**Comment by ChristianErdtmann** [comment]
Ok now i generated a new ipfs link and startet run generate again. 
Aufter that my Images get uploaded and i get now the message:
2 already uploaded.
3 already uploaded.
4 already uploaded.
5 already uploaded.

But i still got the same error by trying to upload the metadata.
When i execute node utils/nftport/uploadMetas.js

I got the error:
ERROR STATUS: 403
Retrying
CATCH ERROR: TypeError: Cannot read properties of undefined (reading 'response')

**Comment by ChristianErdtmann** [comment]
Is Solved

**Comment by natedog1011** [comment]
how

**Comment by sillytechie** [comment]
I had this same problem and figured out the issue was that I did not enter my NFTPort API Key in the .env file.
Once I did that, saved it, ran npm run upload_files and it worked perfectly.
