### ISSUE TITLE
Minted but not on Opensea

### ISSUE THREAD

**Issue by ChristianErdtmann** [codeSTACKr/video-source-code-create-nft-collection#35]
Hey I Minted my NFTs first on rinkaby.
But i dont get acces to the rinkay testnet so i tryied to mint them on polygon.
At First it said
CRYPTOALIENS #1 already minted
CRYPTOALIENS #2 already minted
CRYPTOALIENS #3 already minted
CRYPTOALIENS #4 already minted
But i just minted them to the Rinkeby blockchain not to polygon.

For the rest it says:
Minted: CRYPTOALIENS #6!
Minted: CRYPTOALIENS #7!
Minted: CRYPTOALIENS #8!
Minted: CRYPTOALIENS #9!
Minted: CRYPTOALIENS #10!

Mint.js says that the NFTs are minted and i get no error.
But when i look at my opensee profile there are no new collections or nfts uploaded.

**Comment by ChristianErdtmann** [comment]
I found the collection when i edited a other item so i bring this to the collection. 
Now the collection is visibil but looks like this.
![image](https://user-images.githubusercontent.com/96842089/148700636-c5494f4c-b15a-483d-93aa-4e8fdb3efbdd.png)

**Comment by ChristianErdtmann** [comment]
I have waited now a while but nothing changes and there are only shown the one item i moved manually in the collection 
![image](https://user-images.githubusercontent.com/96842089/148702897-5300bf12-4f38-4b2d-864b-e012383b4ea9.png)

**Comment by ChristianErdtmann** [comment]
But i allready get likes on some of them so i wounder whats wrong.

**Comment by codeSTACKr** [comment]
The collection created using NFTPort would not be open for manually adding to the collection. So I think you are looking at the wrong collection. If you manually created the collection on Opensea, then that could be the issue. It gets created from NFTPort.

**Comment by ChristianErdtmann** [comment]
No i just addeed an existing image to this collection because the collection wasnt shown first.
I now waited some days more but nothing changes the images still not visible
