### ISSUE TITLE
Error Status: 422

### ISSUE THREAD

**Issue by srivera113** [codeSTACKr/video-source-code-create-nft-collection#39]
I get the following error when running utils/nftport/uploadMetas.js 

ERROR STATUS: 422
Retrying
CATCH ERROR: TypeError: Cannot read properties of undefined (reading 'response')
Retrying

**Comment by Sponopolis** [comment]
I've been looking for ways around this for almost 2 days, please help. I feel like I've tried everything at this point.

**Comment by codeSTACKr** [comment]
422 is a server error. NFTPort and the Polygon network have been having issues the past 3 days. Everyone is having the same issues.
