### ISSUE TITLE
Exponential Backoff or Interval

### ISSUE THREAD

**Issue by thorsa12** [codeSTACKr/video-source-code-create-nft-collection#4]
To upload the metadata one would need Exponential Backoff or Interval. How and where could we implement that. 

_ipfsMetas.json 

shows

"code": "quota_limit",
"message": "Too many requests hit the API too quickly. We recommend an exponential backoff of your requests. If you need higher limits see https://nftport.xyz/pricing"

**Comment by codeSTACKr** [comment]
I've fixed this issue by re-writing some of the code. I've added the updates to a new branch.
https://github.com/codeSTACKr/video-source-code-create-nft-collection/tree/fix-uploads-mints
