### ISSUE TITLE
PLS one last help with this I'm going crazy! 😂 it's not an issue with the code. most likely a chain issue. 

### ISSUE THREAD

**Issue by Jakeblackfield** [codeSTACKr/video-source-code-create-nft-collection#40]
it's not an issue with the code. most likely a chain issue.

- can I avoid this just by taking those 1000 minted nfts and upload them directly on OpenSea.io ? will the metadata and all the required files created with the code still be ok if I manually upload them? 

Thanks for the response!

_Originally posted by @codeSTACKr in https://github.com/codeSTACKr/video-source-code-create-nft-collection/issues/37#issuecomment-1009386800_

**Comment by codeSTACKr** [comment]
Sure, you can manually upload them with no issues. It will just take a long time.
