### ISSUE TITLE
handleErrorBinding (can't run min.js)

### ISSUE THREAD

**Issue by Darrklight** [codeSTACKr/video-source-code-create-nft-collection#43]
Hi all, 

I'm by no means an expert and have followed the tutorial without fault till this point, but every time i run "node utils/nftport/mint.js" i get the same error. 

I've searched the forums and can't find a solution. 

Any help would be greatly appreciated. 

<img width="888" alt="Screenshot 2022-01-13 at 12 18 38" src="https://user-images.githubusercontent.com/97475055/149329386-0ca6e5cd-d931-4c35-b1c9-cf9864709d73.png">

**Comment by codeSTACKr** [comment]
The solution is in the error. It cannot find the file `_ipfsMetas.json`. Check your previous steps to track the problem.
