### ISSUE TITLE
i am having canvas.node missing error 

### ISSUE THREAD

**Issue by Umair-Mughal3397** [codeSTACKr/video-source-code-create-nft-collection#45]
Hey Guys i am having this issue what can i do to fix it almost every version is giving me this error 
![image](https://user-images.githubusercontent.com/97691130/149371838-5f020a6a-726f-4a68-931c-f2b56fac6c28.png)

**Comment by codeSTACKr** [comment]
It probably has something to do with your layer folder or file names. Be sure nothing has special characters like dashes.

**Comment by Umair-Mughal3397** [comment]
ok but i am having another issue now

**Comment by Umair-Mughal3397** [comment]
Here 
![image](https://user-images.githubusercontent.com/97691130/149521437-a7c3c94f-1b0b-4a77-b683-777a542dd89f.png)
