### ISSUE TITLE
rror: ENOENT: scandir #-4058

### ISSUE THREAD

**Issue by MurderCro-w** [codeSTACKr/video-source-code-create-nft-collection#47]
![ss](https://user-images.githubusercontent.com/97730316/149491757-3e4f3318-905b-4152-906b-f59714017287.png)
 

I have tried : npm rebuild node-sass, npm update , npm install node-fetch@2 (after ) the uninstall.

Unable to find anything else on the WEB regarding this... any info is appreciated!

**Comment by rainbowsprinklefroyo** [comment]
I'm getting the same error. Was this resolved? @MurderCro-w
