### ISSUE TITLE
Error result from command at 32.30 of video (first ipfs upload) "error:TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined"

### ISSUE THREAD

**Issue by hlairboltons** [codeSTACKr/video-source-code-create-nft-collection#5]
I am using 10 webp files with 10 valid JSON. Some files are successfully updated to ipfs and can be viewed in browser, but others dont unless I redo the command a dozen times. I also have 10,000 images i want to upload so this is probably not viable. Log attached, thanks :)

PS C:\Users\blair\OneDrive\Documents\Komodo_Joe\NFTPortUpload\video-source-code-create-nft-collection-main> node utils/nftport/uploadFiles.js
error:TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
error:TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Rerror:TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
error:TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
error:TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
error:TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
1.webp uploaded & 1.json updated!
2.webp uploaded & 2.json updated!
6.webp uploaded & 6.json updated!
8.webp uploaded & 8.json updated!
PS C:\Users\blair\OneDrive\Documents\Komodo_Joe\NFTPortUpload\video-source-code-create-nft-collection-main> node utils/nftport/uploadFiles.js
error:TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
error:TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Rerror:TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
error:TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
error:TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
error:TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
8.webp uploaded & 8.json updated!
2.webp uploaded & 2.json updated!
1.webp uploaded & 1.json updated!
4.webp uploaded & 4.json updated!
PS C:\Users\blair\OneDrive\Documents\Komodo_Joe\NFTPortUpload\video-source-code-create-nft-collection-main> node utils/nftport/uploadFiles.js
error:TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
error:TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
error:TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
error:TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
error:TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
error:TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
5.webp uploaded & 5.json updated!
8.webp uploaded & 8.json updated!
7.webp uploaded & 7.json updated!
2.webp uploaded & 2.json updated!
PS C:\Users\blair\OneDrive\Documents\Komodo_Joe\NFTPortUpload\video-source-code-create-nft-collection-main>

**Comment by sonuaa** [comment]
same problem for me

**Comment by badxwolfyz** [comment]
any fix ?

**Comment by comancosmin** [comment]
I have the same issue! 

I have 20 images and all the time when i run the command i have only 2 or 3 files uploaded. 
`PS C:\Users\Cosmin\Desktop\hashlips_art_engine-1.1.1_update> node utils/nftport/uploadFiles.js
Error: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
Error: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
Error: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
Error: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
Error: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
Error: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
Error: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
Error: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
Error: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
Error: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
Error: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
Error: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
Error: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
Error: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
Error: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
Error: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
Error: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
Error: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
1.png uploaded & 1.json updated!
16.png uploaded & 16.json updated!`

**Comment by afrikaxtract** [comment]
Same problem here - I wonder if this is because you need to have a paid nftport account and therefore you are limited. hope theres a fix. using a macbook pro M1

**Comment by econcepcion** [comment]
Anyone figure this out?

error:TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined

Thanks

**Comment by hendrikegn** [comment]
Hello! I'm having the same issue for all 100 files I'm trying to upload. Thank you very much for your support ! happy and safe holidays !

**Comment by comancosmin** [comment]
Problem fixed on me! Download last version!

**Comment by hendrikegn** [comment]
> 

Hello, last version of what exactly? thanks!

**Comment by comancosmin** [comment]
From here: https://github.com/codeSTACKr/video-source-code-create-nft-collection

Press on Code -> Download ZIP file and then copy the src and utils folders to your own. 
Config your files again: *config.js, uploadFiles.js, uploadMetas.js and mint.js*

**Comment by hendrikegn** [comment]
Yes! is working now! Thank you!

**Comment by codeSTACKr** [comment]
Fixed with latest code:
https://github.com/codeSTACKr/video-source-code-create-nft-collection/tree/fix-uploads-mints
