### ISSUE TITLE
Error when uploading metas to IPFS

### ISSUE THREAD

**Issue by hlairboltons** [codeSTACKr/video-source-code-create-nft-collection#6]
I am still experiencing issues with my issue request, however I have managed to get 10 test JSONs linked to valid IPFS urls, so I decided to proceed as a test run  

When I attempt to proceed to uploading metadata to IPFS via the command **node utils/nftport/uploadMetas.js** 
, I get the error:

**PS C:\Users\OneDrive\Documents\Komodo_Joe\NFTPortUpload\video-source-code-create-nft-collection-main> node utils/nftport/uploadMetas.js
undefined metadata uploaded & added to _ipfsMetas.json
undefined metadata uploaded & added to _ipfsMetas.json
undefined metadata uploaded & added to _ipfsMetas.json
undefined metadata uploaded & added to _ipfsMetas.json
undefined metadata uploaded & added to _ipfsMetas.json
undefined metadata uploaded & added to _ipfsMetas.json
undefined metadata uploaded & added to _ipfsMetas.json
undefined metadata uploaded & added to _ipfsMetas.json
undefined metadata uploaded & added to _ipfsMetas.json
undefined metadata uploaded & added to _ipfsMetas.json**

As can be seen in my attached code the _ipfsMetas.json file content is not matching my seperated JSON files or _metadata.json file.

NOTE: I **did not** use the hashlips generator to create my images and metadata, however my JSON is valid. Any idea of fix?
Thank you for the great content :)

**Comment by codeSTACKr** [comment]
fixed with latest code:
https://github.com/codeSTACKr/video-source-code-create-nft-collection/tree/fix-uploads-mints
