### ISSUE TITLE
error:FetchError: request to https://api.nftport.xyz/v0/files failed, reason: read ECONNRESET

### ISSUE THREAD

**Issue by rezainshafa** [codeSTACKr/video-source-code-create-nft-collection#7]
error:FetchError: invalid json response body at https://api.nftport.xyz/v0/files reason: Unexpected token < in JSON at position 1
error:FetchError: request to https://api.nftport.xyz/v0/files failed, reason: connect ETIMEDOUT 34.120.251.101:443
error:FetchError: request to https://api.nftport.xyz/v0/files failed, reason: read ECONNRESET

Note : I got this error when I wanted to upload an image to ipfs using the command "node utils/nftport/uploadFiles.js" I don't know where the error is but it seems to refer to the api from nftport.xyz. please help me, thank you

**Comment by rossxdev** [comment]
Nftport was updating their infrastructure. I think this issue was in their end and is resolved now.

**Comment by bryanblaz** [comment]
> error:FetchError: invalid json response body at https://api.nftport.xyz/v0/files reason: Unexpected token < in JSON at position 1 error:FetchError: request to https://api.nftport.xyz/v0/files failed, reason: connect ETIMEDOUT 34.120.251.101:443 error:FetchError: request to https://api.nftport.xyz/v0/files failed, reason: read ECONNRESET
> 
> Note : I got this error when I wanted to upload an image to ipfs using the command "node utils/nftport/uploadFiles.js" I don't know where the error is but it seems to refer to the api from nftport.xyz. please help me, thank you

Have you figured out why were you getting this message? I am also getting it.

**Comment by codeSTACKr** [comment]
fixed with latest code:
https://github.com/codeSTACKr/video-source-code-create-nft-collection/tree/fix-uploads-mints
