### ISSUE TITLE
"null metadata uploaded & added to _ipfsMetas.json"

### ISSUE THREAD

**Issue by LudRodhz** [codeSTACKr/video-source-code-create-nft-collection#8]
null metadata uploaded & added to _ipfsMetas.json
44.30

when loading my ipfs files this happens:
...
...
...
Unknown metadata uploaded & added to _ipfsMetas.json
Unknown metadata uploaded & added to _ipfsMetas.json
Unknown metadata uploaded & added to _ipfsMetas.json
null metadata uploaded & added to _ipfsMetas.json
null metadata uploaded & added to _ipfsMetas.json
null metadata uploaded & added to _ipfsMetas.json
...
...
...

**Comment by chaze117** [comment]
I have almost the same issue except most of the files not uploading and the error message is: 
`error:TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined`

**Comment by codeSTACKr** [comment]
fixed with latest code:
https://github.com/codeSTACKr/video-source-code-create-nft-collection/tree/fix-uploads-mints
