### ISSUE TITLE
error:TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by alexshibu1** [codeSTACKr/video-source-code-create-nft-collection#9]
I keep getting this issues even after using the new branch. Some uploads work others don't. Could it be with the syntax of the layers itself?

**Comment by alexshibu1** [comment]
Just cloned the new branch again and it worked

**Comment by afrikaxtract** [comment]
Hey Alex, running a Macbookpro with M1 I have cloned the new branch after writing the code myself, generate 5 images but after trying to upload with my API key still getting the same issues where only 2 out of the 5 are uploading. any idea of what caused this or the issue around it?

**Comment by alexshibu1** [comment]
I think it might be a m1 issue. I switched to razer and it worked fine.

**Comment by afrikaxtract** [comment]
aaah i see. do you think if i just used xcode it would work? where can i find razer? are you also using a m1?

**Comment by alexshibu1** [comment]
I meant the razer windows laptop. Something is weird with the m1's and getting all of it working. I used vscode on both devices. I'm not really familiar with xcode. It might work. Are you trynna do this for polygon?

**Comment by ChristianErdtmann** [comment]
Hey i tried what you said and cloned the branch again but it still dont working. i still got the error error:TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined 
any tips for fix?

**Comment by alexshibu1** [comment]
maybe try the hashlips repo.
